spring:
  config:
    import: optional:classpath:ignore/oauth2-resourceserver.yaml
  cloud:
    gateway:
      routes:
        - id: toygry-api-1
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<path>.*), /$\{path}
        - id: toygry-api-2
          uri: http://localhost:8082
          predicates:
            - Path=/api2/**
          filters:
            - RewritePath=/api2/(?<path>.*), /$\{path}
      default-filters:
        - name: GlobalFilter
          args:
            postLogger: true
  main:
    web-application-type: reactive
server:
  port: 8080

