server:
  port: 8081

spring:
  config:
    import: optional:classpath:ignore/pg-info.yaml
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect